"""Shared Pydantic models for OneData-enabled Domino pieces."""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class OneDataSecretsModel(BaseModel):
  """Optional OneData credentials. When host+token are set, onedata:/// paths
  are read from OneData and outputs mirror to
  ``<onedata_output_dir>/<run_id>/<PieceName>/``."""

  onedata_onezone_host: Optional[str] = Field(
      default=None,
      description="Onedata Onezone host, e.g. data.spice-platform.eu",
  )
  onedata_token: Optional[str] = Field(
      default=None,
      description="Onedata access token — set in Domino workflow secrets (not in git)",
  )
  onedata_output_dir: Optional[str] = Field(
      default=None,
      description="OneData base dir for run outputs, e.g. onedata:///FilipsSpace/cost_optimizer/outputs",
  )


class RunIdInputMixin(BaseModel):
  """Propagated from UserInputPiece so each run writes to its own output subfolder."""

  run_id: str = Field(
      default="",
      description="Workflow run id (generated by UserInputPiece when using OneData)",
  )
